export  const ADD_ITEM = 'ADD_ITEM'
export  const REMOVE_ITEM = 'REMOVE_ITEM'
export  const ADD_ITEM_HISTORY = 'ADD_ITEM_HISTORY'
export  const REMOVE_HISTORY = 'REMOVE_HISTORY'
export  const UPDATE_TIMER = 'UPDATE_TIMER'
